CREATE TABLE ai_providers (
  id VARCHAR(36) NOT NULL COMMENT 'AI 厂商主键 ID',
  code VARCHAR(50) NOT NULL COMMENT '厂商唯一编码',
  name VARCHAR(100) NOT NULL COMMENT '厂商显示名称',
  description VARCHAR(255) NULL COMMENT '厂商描述',
  icon_url TEXT NULL COMMENT '厂商图标地址',
  base_url TEXT NOT NULL COMMENT '厂商基础地址',
  api_key_encrypted LONGTEXT NULL COMMENT '加密后的 API Key',
  api_key_hint VARCHAR(64) NULL COMMENT 'API Key 脱敏提示',
  chat_endpoint VARCHAR(255) NOT NULL DEFAULT '/chat/completions' COMMENT '对话端点',
  image_endpoint VARCHAR(255) NOT NULL DEFAULT '/images/generations' COMMENT '图片端点',
  video_endpoint VARCHAR(255) NOT NULL DEFAULT '/videos' COMMENT '视频端点',
  default_chat_model VARCHAR(191) NULL COMMENT '默认对话模型',
  supported_types_json JSON NULL COMMENT '支持的模型分类 JSON',
  is_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  is_built_in TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否系统内置',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序值',
  extra_json JSON NULL COMMENT '扩展配置 JSON',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ai_providers_code (code),
  KEY idx_ai_providers_enabled_sort (is_enabled, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 厂商实体表';

CREATE TABLE ai_models (
  id VARCHAR(36) NOT NULL COMMENT 'AI 模型主键 ID',
  provider_id VARCHAR(36) NOT NULL COMMENT '所属厂商 ID',
  category ENUM('CHAT', 'IMAGE', 'VIDEO') NOT NULL COMMENT '模型分类',
  name VARCHAR(100) NOT NULL COMMENT '模型显示名称',
  model_key VARCHAR(191) NOT NULL COMMENT '模型标识',
  description VARCHAR(255) NULL COMMENT '模型描述',
  capability_json JSON NULL COMMENT '模型能力 JSON',
  default_params_json JSON NULL COMMENT '模型默认参数 JSON',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序值',
  is_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  is_built_in TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否系统内置',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ai_models_provider_category_key (provider_id, category, model_key),
  KEY idx_ai_models_provider_category_sort (provider_id, category, sort_order),
  KEY idx_ai_models_enabled_category (is_enabled, category),
  CONSTRAINT fk_ai_models_provider_id FOREIGN KEY (provider_id) REFERENCES ai_providers(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 模型实体表';
