import type { TextElement } from "@cutia/types/timeline";
import { TIMELINE_CONSTANTS } from "./timeline-constants";

export type SubtitleTemplate = Omit<
	TextElement,
	"id" | "startTime" | "trimStart" | "trimEnd" | "duration"
> & {
	templateId: string;
	templateName: string;
};

export const SUBTITLE_TEMPLATES: SubtitleTemplate[] = [
	{
		templateId: "classic",
		templateName: "Classic",
		type: "text",
		name: "Subtitle",
		content: "Your subtitle here",
		fontSize: 5,
		fontFamily: "Arial",
		color: "#ffffff",
		backgroundColor: "rgba(0, 0, 0, 0.7)",
		textAlign: "center",
		fontWeight: "normal",
		fontStyle: "normal",
		textDecoration: "none",
		opacity: 1,
		transform: { scale: 1, position: { x: 0, y: 300 }, rotate: 0 },
	},
	{
		templateId: "modern",
		templateName: "Modern",
		type: "text",
		name: "Subtitle",
		content: "Your subtitle here",
		fontSize: 5,
		fontFamily: "Inter",
		color: "#ffffff",
		backgroundColor: "transparent",
		textAlign: "center",
		fontWeight: "bold",
		fontStyle: "normal",
		textDecoration: "none",
		opacity: 1,
		transform: { scale: 1, position: { x: 0, y: 300 }, rotate: 0 },
	},
	{
		templateId: "minimal",
		templateName: "Minimal",
		type: "text",
		name: "Subtitle",
		content: "Your subtitle here",
		fontSize: 5,
		fontFamily: "Helvetica",
		color: "#ffffff",
		backgroundColor: "transparent",
		textAlign: "center",
		fontWeight: "normal",
		fontStyle: "normal",
		textDecoration: "none",
		opacity: 0.9,
		transform: { scale: 1, position: { x: 0, y: 280 }, rotate: 0 },
	},
	{
		templateId: "highContrast",
		templateName: "High Contrast",
		type: "text",
		name: "Subtitle",
		content: "Your subtitle here",
		fontSize: 5,
		fontFamily: "Arial",
		color: "#ffff00",
		backgroundColor: "rgba(0, 0, 0, 0.85)",
		textAlign: "center",
		fontWeight: "bold",
		fontStyle: "normal",
		textDecoration: "none",
		opacity: 1,
		transform: { scale: 1, position: { x: 0, y: 300 }, rotate: 0 },
	},
	{
		templateId: "news",
		templateName: "News Style",
		type: "text",
		name: "Subtitle",
		content: "Your subtitle here",
		fontSize: 5,
		fontFamily: "Arial",
		color: "#ffffff",
		backgroundColor: "rgba(0, 100, 200, 0.9)",
		textAlign: "center",
		fontWeight: "bold",
		fontStyle: "normal",
		textDecoration: "none",
		opacity: 1,
		transform: { scale: 1, position: { x: 0, y: 320 }, rotate: 0 },
	},
	{
		templateId: "karaoke",
		templateName: "Karaoke",
		type: "text",
		name: "Subtitle",
		content: "Your subtitle here",
		fontSize: 6,
		fontFamily: "Impact",
		color: "#00ffff",
		backgroundColor: "transparent",
		textAlign: "center",
		fontWeight: "bold",
		fontStyle: "normal",
		textDecoration: "none",
		opacity: 1,
		transform: { scale: 1, position: { x: 0, y: 0 }, rotate: 0 },
	},
	{
		templateId: "cinematic",
		templateName: "Cinematic",
		type: "text",
		name: "Subtitle",
		content: "Your subtitle here",
		fontSize: 5,
		fontFamily: "Georgia",
		color: "#ffffff",
		backgroundColor: "transparent",
		textAlign: "center",
		fontWeight: "normal",
		fontStyle: "italic",
		textDecoration: "none",
		opacity: 0.95,
		transform: { scale: 1, position: { x: 0, y: 280 }, rotate: 0 },
	},
	{
		templateId: "topTitle",
		templateName: "Top Title",
		type: "text",
		name: "Subtitle",
		content: "Your subtitle here",
		fontSize: 5,
		fontFamily: "Arial",
		color: "#ffffff",
		backgroundColor: "rgba(0, 0, 0, 0.6)",
		textAlign: "center",
		fontWeight: "bold",
		fontStyle: "normal",
		textDecoration: "none",
		opacity: 1,
		transform: { scale: 1, position: { x: 0, y: -300 }, rotate: 0 },
	},
];

export function createSubtitleFromTemplate({
	template,
	startTime = 0,
}: {
	template: SubtitleTemplate;
	startTime?: number;
}): Omit<TextElement, "id"> {
	const {
		templateId: _templateId,
		templateName: _templateName,
		...elementProps
	} = template;
	return {
		...elementProps,
		duration: TIMELINE_CONSTANTS.DEFAULT_ELEMENT_DURATION,
		startTime,
		trimStart: 0,
		trimEnd: 0,
	};
}
